### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by garrison** [doncabreraphone/victorhugo#1]
Hello.  Well done!  And thank you.

Here are a few issues that I noticed while getting this working:

- My site uses the `defer` attribute on the `<script>` tag that loads jQuery, which means jQuery is not loaded before inline Javascript, which meant initially that victorhugo was broken on my site.  I fixed this by changing [this line](https://github.com/doncabreraphone/victorhugo/blob/23f92f6f86f2fb506e679b44c715546f10f4ffc3/victorhugo.html#L14) to instead say `window.addEventListener('DOMContentLoaded', function(){`, which removes the dependency on jQuery until after it has loaded, even if it is marked `defer`.
- victorhugo fails completely if the `<meta name="description">` tag is missing entirely.  In my case, I had included the partial `{{ template "_internal/schema.html" . -}}`, which has `itemprop` as its attribute instead of `name`.  Not sure what the difference is, but ideally this wouldn't cause the code to fail entirely.

Once I resolved these two issues, victorhugo is very informative.

**Comment by doncabreraphone** [comment]
Hello Garrison,

You are welcome, I hope you find it as useful as I'm finding it. Hugo really needed something like this. Your changes have been added and the code is now updated. About the ``<meta name="description">``, I'm afraid you actually needed to have that one. Google is always saying things like "oh don't worry, our magical algorithm will read your content anyway", but the truth is Google is not the only search engine in town. We now have DuckDuckGo, Bing, Baidu, Yandex, and many more, and they **do** relay on meta description to run their businesses. 

You can always relay on the _meta tags_ to get your site in front of search engines.

Schema is more for meta data. Google``upcoming events`` and you will see what I mean. Using Schema just to display your post title and description is... kind of like using a Ferrari to go around the block. Yes, you can, and you will be doing it with style, but there is so much more you can do with a Ferrari besides taking selfies on the curb with strangers. <a href="https://Schema.org">Schema.org</a> has a ton of information on how you can use and tweak Hugo's internal schema template. The more data you throw at Search Engines, the more they will crawl your site.

Victor Hugo focuses on the basis, on the _meta tags_, but I'm planning on updating it to include Schema (although the scope of Schema is so large it will take a while for me to go through all the specs). As it is, Victor Hugo makes for a pretty good replacement for the Yoast plugin.

Thanks for stopping by!

Let me know if the fixes work for you and I will close this issue.

**Comment by garrison** [comment]
> About the `<meta name="description">`, I'm afraid you actually needed to have that one.

Interesting.  I am using the ananke theme, which is mentioned in the Hugo [quick start](https://gohugo.io/getting-started/quick-start/), so I had assumed that whatever it is doing must be sufficient.

**Comment by doncabreraphone** [comment]
That is the main problem with SEO, whatever you do, it will never be
sufficient. You can spend a lifetime optimizing your site and boom, Google
or someone else makes a change to some obscure algorithm and boom! The best
thing to do, in my opinion, but don't quote me on that, is to optimize your
content the best you can, the simplest way you can, and then focus on
interacting with people. Search Engines are a good source of traffic, but
I've had a site with +150k visits a month where no one wanted to pay $1 for
a product. Better to have 500 visitors who want to pay $2, know you, know
your product or service and come back often for more, than have +150k
visitors who come through the door because Google ranked you high on a few
keywords and bounce in 2 seconds out to the streets again.

**Comment by garrison** [comment]
Works for me now out of the box.  Thank you!  Closing this issue.
